### ISSUE TITLE
Header and footer social nav menus don't work

### ISSUE THREAD

**Issue by gregjd** [sunlightlabs/sfcom-wordpress-theme#32]
The links don't link to anything.

Also, for the GitHub icon, there are three things it could link to:
1. https://github.com/sunlightlabs — in the olden days we might have done this, but since Labs is closing, this doesn't seem to make much sense
2. https://github.com/sunlightpolicy — the only part of Sunlight that will still be around
3. https://github.com/sunlightlabs/sfcom-wordpress-theme — the GitHub repo for the site itself

My vote would be for option 3, followed by 2. Definitely not 1.

**Comment by krusynth** [comment]
Following the `principle of least astonishment`, I think it makes the most sense to remove the GH link altogether.  Policy !== Sunlight as a whole, so that doesn't make sense to me. Labs' repos will continue to exist, but I agree that it doesn't make sense to point there.  Pointing a social link to the theme itself makes no sense to me as a user.

**Comment by krusynth** [comment]
Fixed the links.

**Comment by krusynth** [comment]
Removed it.
